- hosts: web
  become: yes

  tasks:

  - name: Install Nginx Web Server
    yum:
      name: http://nginx.org/packages/rhel/7/x86_64/RPMS/nginx-1.12.1-1.el7.ngx.x86_64.rpm
      state: present

  - name: Start Nginx service
    service: name=nginx state=started enabled=yes

  - name: write the apache config file
    copy: src=nginx_upstream.conf dest=/etc/nginx/nginx.conf
    notify:
      - Restart Nginx service

  handlers:
    - name: Restart Nginx service
      service: name=nginx state=restarted


- hosts: app
  become: yes
  tasks:

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
      dest: /usr/local/
      remote_src: yes

  - name: Add to golang PATH environment variable
    shell: export PATH=$PATH:/usr/local/go/bin
    args:
      executable: /bin/bash

  - name: enable PATH environment variable
    shell: source $HOME/.bash_profile
    args:
      executable: /bin/bash

  - name: Copy Golang Application code to App servers
    copy: src=main.go dest=/usr/local/go/src/myapp/

  - name: This command will run the golang application
    command: /usr/local/go/bin/go run main.go
    args:
      chdir: /usr/local/go/src/myapp
